spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/shoppy
    username: ${POSTGRES_USER:shoppy}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

courses:
  service:
    url: http://catalog-service:8080/api/courses
