spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shoppy
    username: shoppy
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

courses:
  service:
    url: http://localhost:8081/api/courses
