server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: http://catalog-service:8080
          predicates:
            - Path=/api/products/**, /api/categories/**, /api/units/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter

        - id: users-service
          uri: http://users-service:8080
          predicates:
            - Path=/api/users/**, /api/regions/**, /api/comunas/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: http://users-service:8080
          predicates:
            - Path=/api/auth/**

        - id: supports-service
          uri: http://supports-service:8080
          predicates:
            - Path=/api/supports/**
          filters:
            - AuthenticationFilter

        # Swagger per service (prefijo /catalog|/users|/order|/supports)
        - id: catalog-swagger
          uri: http://catalog-service:8080
          predicates:
            - Path=/catalog/swagger-ui/**, /catalog/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: users-swagger
          uri: http://users-service:8080
          predicates:
            - Path=/users/swagger-ui/**, /users/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: order-swagger
          uri: http://order-service:8080
          predicates:
            - Path=/order/swagger-ui/**, /order/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: supports-swagger
          uri: http://supports-service:8080
          predicates:
            - Path=/supports/swagger-ui/**, /supports/v3/api-docs/**
          filters:
            - StripPrefix=1

shoppy:
  app:
    jwtSecret: ${JWT_SECRET:shoppySecretKey12345678901234567890123456789012}
