server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/shoppy
    username: ${POSTGRES_USER:shoppy}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

shoppy:
  app:
    jwtSecret: ${JWT_SECRET:shoppySecretKey12345678901234567890123456789012}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /users/v3/api-docs
    config-url: /users/v3/api-docs
    urls:
      - name: Users API
        url: /users/v3/api-docs
